/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class util_NativeMatrix4 */

#ifndef _Included_util_NativeMatrix4
#define _Included_util_NativeMatrix4
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     util_NativeMatrix4
 * Method:    invert
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_util_NativeMatrix4_invert
  (JNIEnv *, jclass, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
